spring:
    datasource: 
        url: jdbc:mysql://localhost:3306/helpdesk
        username: root
        password: 
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect

